### ISSUE TITLE
Add Template for issue generation

### ISSUE THREAD

**Issue by k-deepak04** [Deveimer/vovoca-frontend#10]
i can creat one template for creating the issue so it would be in proper format
with idea/functionality and bug as option

![image](https://github.com/Deveimer/vovoca-frontend/assets/96341431/ec56da15-795f-40d2-bdcd-188c3f83c346)
![image](https://github.com/Deveimer/vovoca-frontend/assets/96341431/8c5db460-dbd4-4072-b6e1-6e9fb9b5bf1d)

this will help to properly describe issue and maintain proper code of conduct rather than random issue generating

please assign this to me under GSSOC label

**Comment by kaustubhai** [comment]
Dont need it.
