### ISSUE TITLE
Improving the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [Deveimer/vovoca-frontend#105]
## Issue Description

Hello there!
I would like to work on the README.md to make it more visually appealing and coherent.
I will:
+ restructure the header
+ better styling of content
+ fix some errors in the README.md
+ format the text in a better manner
+ add badges 
+ etc.

Do assign me for **GSSOC'23** if approved

**Comment by Titiksha2012** [comment]
@varun-singhh Kindly assign me this issue. I'm keen working on this.

**Comment by kaustubhai** [comment]
@the-amazing-atharva still interested?

**Comment by Titiksha2012** [comment]
@kaustubhai Yes sir, plz assign this to me

**Comment by the-amazing-atharva** [comment]
> @the-amazing-atharva still interested?

Yup, working on it!
Do assign me with GSSOC'23

**Comment by kaustubhai** [comment]
@Titiksha2012 please try to create your issues, cannot assign you someone else's created issues
