### ISSUE TITLE
Footer Section Improvement 

### ISSUE THREAD

**Issue by ghoshvidip26** [Deveimer/vovoca-frontend#107]
## Issue Description

Footer Section is distorted for smaller and medium devices like words getting overlapped, overflow etc.

## Steps to Reproduce (if applicable)

1. [Step 1]
2. [Step 2]
3. [Step 3]

## Expected Behavior

No overlapping of contents

## Current Behavior

Overflow and Overlapped contents. 
![image](https://github.com/Deveimer/vovoca-frontend/assets/91741581/d64ad00e-00df-4e1c-8ed7-4ff93d7549aa)
![image](https://github.com/Deveimer/vovoca-frontend/assets/91741581/6e42e07c-3fef-4af2-9dd8-a1604632d2fd)
![image](https://github.com/Deveimer/vovoca-frontend/assets/91741581/0edd2089-153c-4b68-b078-0cfa1a98b929)

## Possible Solution (optional)

[Provide suggestions or ideas for how to address this issue.]

## Additional Context (optional)

I would like to work on this issue under GSSOC'23.

**Comment by kaleemullah786** [comment]
this seems doable to me by adding media queries and resizing elements accordingly.
I would like to work on this issue under GSSOC'23

**Comment by mkmahmud** [comment]
Based on the provided images, it seems that the footer section of your website is experiencing layout issues on smaller and medium devices, causing words to overlap and resulting in overflow. To resolve these problems, we can try the following steps: 

1. Implement Responsive CSS
2. Handle Long Text
3. Reduce Content or Reorganize
4. Utilize Flexbox or Grid

We can apply CSS properties like word-wrap: break-word; or overflow-wrap: break-word; to ensure that long words wrap within the available space. 

I am interested to work on this issue under GSSOC'23

**Comment by kaustubhai** [comment]
It looks fine till 300px and we are fine with it as of now. For tablet mode, we are still working on it so we can ignore it. Hence, we don't require these changes as of now, Thanks though
