### ISSUE TITLE
Image not showing in Team section

### ISSUE THREAD

**Issue by sumitkr2000** [Deveimer/vovoca-frontend#108]
## Issue Description

Hey, @varun-singhh The images on the sided cards are not showing and because of this, the page is not looking good. I want to add images to it. Please assign me this issue.

## Steps to Reproduce (if applicable)

1. Add images to teams cards
2. [Step 2]
3. [Step 3]

## Expected Behavior

[Describe what you expected to happen.]

## Current Behavior

[Describe what actually happened.]

## Possible Solution (optional)

[Provide suggestions or ideas for how to address this issue.]

## Additional Context (optional)

[Add any other relevant information here, such as screenshots, related issues, or notes.]

**Comment by SurbhiMotwani23** [comment]
please assign me this issue

**Comment by kaustubhai** [comment]
This is not a code-level issue that contributors can fix. Thanks though for the issue

**Comment by sumitkr2000** [comment]
I thought it is a bug that's why i raised this issue. Anyway np!
