### ISSUE TITLE
Add social button in the footer

### ISSUE THREAD

**Issue by sumitkr2000** [Deveimer/vovoca-frontend#109]
## Issue Description

Hey @varun-singhh I want to add social icons in the footer. Please assign me this issue. Thank you!

## Steps to Reproduce (if applicable)

1. Add social icons of GitHub, discord, insta, etc.
2. [Step 2]
3. [Step 3]

## Expected Behavior

[Describe what you expected to happen.]

## Current Behavior

[Describe what actually happened.]

## Possible Solution (optional)

[Provide suggestions or ideas for how to address this issue.]

## Additional Context (optional)

[Add any other relevant information here, such as screenshots, related issues, or notes.]

**Comment by kaustubhai** [comment]
Not required as of now, thanks
