### ISSUE TITLE
[Feature] Implement a Hamburger Menu for tablet Mode. [GSSoC'23]

### ISSUE THREAD

**Issue by vishnu9865** [Deveimer/vovoca-frontend#111]
## Issue Description
 - The navbar become wrapped on tablet mode and mobile navbar at bottom is not suitable for tablet usage ( where the hands are neither at the bottom nor at the top).
 - I would like to propose a hamburger menu for tablet screen size therefore easier for tablet users to reach (better UX).
 - This will also improve the look of the website (better UI).

## Expected Behavior
 - Have a Hamburger menu for tablet screens.

## Current Behavior
![image](https://github.com/Deveimer/vovoca-frontend/assets/91585213/8521466c-c0b9-4cf8-82cf-48e8b8b8ec55)

**Comment by kaustubhai** [comment]
You are suggesting 3 menus for a single website:
1. Full menu for desktop
2. Hamburger menu for tablet
3. Bottom menu for phones

This is not required as of now, thanks
