### ISSUE TITLE
Divs in testimonial page are not showing uniformity

### ISSUE THREAD

**Issue by vishwabandita** [Deveimer/vovoca-frontend#112]
## Issue Description
UI of testimonial page is not following uniformity.

## Steps to Reproduce (if applicable)

Divs in testimonial page are not assigned equal heights which is showing uneveness and not making it visually appealing.

## Expected Behavior

All the divs will have equal sizes which will make it look more professional. Aliging the rows and column having unifromity.

**Comment by kaustubhai** [comment]
This is not required rn, thanks
