### ISSUE TITLE
Footer div is not placed in center

### ISSUE THREAD

**Issue by SimardeepSingh1450** [Deveimer/vovoca-frontend#113]
## Issue Description

[Describe the problem or request here.]
Here is a screenshot of alignment of the footer's DIV : 

![content-not-in-center](https://github.com/Deveimer/vovoca-frontend/assets/92221517/59b350e3-deac-4f2d-a9c0-1601c65e79f2)

## Steps to Reproduce (if applicable)

1. Visit the Site, see the footer alignment

## Expected Behavior
Should be placed in center i guess.

## Current Behavior
Not placed in center, slightly aligned towards left.

## Possible Solution (optional)
1. Fixing the CSS should do the job.

**Comment by SimardeepSingh1450** [comment]
If you want @varun-singhh I can work on this issue under GSSoC?

**Comment by kaustubhai** [comment]
Please go ahead.

**Comment by varun-singhh** [comment]
already fixed
