### ISSUE TITLE
VVCA | [Enhancement] Style footer component

### ISSUE THREAD

**Issue by singodiyashubham87** [Deveimer/vovoca-frontend#115]
## Issue Description

The footer of the website landing page is not aligned which is making the website look inconsistent

## Steps to Reproduce (if applicable)

1. Clone the project
2. Align the footer div
3. Commit changes and make PR

![Screenshot from 2023-06-02 10-43-53](https://github.com/Deveimer/vovoca-frontend/assets/93720428/ccb4e270-6ae4-4265-90a4-38746667e6bc)

**Comment by singodiyashubham87** [comment]
@chris--jones Kindly assign me this issue under GSSOC'23

**Comment by kaustubhai** [comment]
Which page and what screen size is this?

**Comment by singodiyashubham87** [comment]
@kaustubhai It's the landing page itself.

**Comment by kaustubhai** [comment]
![image](https://github.com/Deveimer/vovoca-frontend/assets/47121025/7fa579be-cad0-410d-aab6-c2e6284665b6)


My landing page footer is different from yours?

**Comment by singodiyashubham87** [comment]
@kaustubhai Website link.

**Comment by varun-singhh** [comment]
already assigned to someone
