### ISSUE TITLE
Footer Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [Deveimer/vovoca-frontend#116]
## Issue Description

Footer Section is needed in the website . 

## Expected Behavior
There should be Footer Section in the website . 

## Current Behavior

[Describe what actually happened.]

## Possible Solution (optional)

[Provide suggestions or ideas for how to address this issue.]

## Additional Context (optional)
https://github.com/Deveimer/vovoca-frontend/assets/85991449/8808a2b2-956f-4589-be2c-649b129f789a

**Comment by parthpathakpp1** [comment]
Already assigned issue https://github.com/Deveimer/vovoca-frontend/issues/2

**Comment by kaustubhai** [comment]
> Already assigned issue [#2](https://github.com/Deveimer/vovoca-frontend/issues/2)

Then why have you raised a new issue?
