### ISSUE TITLE
[Improvements] In the About Us, Testimonials and Team Section

### ISSUE THREAD

**Issue by Anshika-Jain02** [Deveimer/vovoca-frontend#12]
## Here are Two Issues that I would like to work on:-
*Issue -1  The Height of all cards is not the same in the Team and Testimonials section. We can resolve this issue to bring consistency to the page.*
*Issue -2 The Circle image is getting overflow from its respective div.*

**Please assign me these issues under Gssoc'23 @varun-singhh**

![vovoca](https://github.com/Deveimer/vovoca-frontend/assets/104912087/d79f2d45-78d0-43b0-a6fd-b43977c27e39)
![vovoca 3](https://github.com/Deveimer/vovoca-frontend/assets/104912087/4805edef-a3ed-4a25-87b2-91dedc3b00eb)
![vovoca 2](https://github.com/Deveimer/vovoca-frontend/assets/104912087/9cd5613d-0350-4976-851c-d32644f658ec)

**Comment by varun-singhh** [comment]
@Anshika-Jain02 assigned

**Comment by Anshika-Jain02** [comment]
Sir, should I make the changes in a separate branch and then send you the PR?

**Comment by parthpathakpp1** [comment]
@Anshika-Jain02 need some help . Can you share your discord id .

**Comment by Anshika-Jain02** [comment]
Anshika #8204 @parthpathakpp1

**Comment by parthpathakpp1** [comment]
> Anshika #8204 @parthpathakpp1

check DM.
