### ISSUE TITLE
Add Hover Effects in Testimonial

### ISSUE THREAD

**Issue by justankiit** [Deveimer/vovoca-frontend#120]
## Issue Description

If we see in the below in Testimonial Section, There isn't any Existing Hovering Effect, Which Doesn't looks good

![image](https://github.com/Deveimer/vovoca-frontend/assets/111564362/a43ef3ad-3a84-4e2b-9942-ceb849ad7b05)

## Expected Behavior

We Can add a hover effect of cursor and the size of this card will be increased, These type of testimonial effects can be look good.

**Comment by kaustubhai** [comment]
Hover effect is not expected behaviour and is not required. Thanks
