### ISSUE TITLE
Enlargement of 'login here' text at the bottom of the signup form.

### ISSUE THREAD

**Issue by Titiksha2012** [Deveimer/vovoca-frontend#122]
The text at the bottom of the signup form saying:
'Already have an account...' is too small to read.

I feel the to need to enlarge to make it readable to the user for avoiding any inconvenience and saving it from being unnoticeable.

Here is a screenshot of the above mentioned problem:
![image](https://github.com/Deveimer/vovoca-frontend/assets/112792296/182ab045-9b9d-4b00-97d9-8a3460fa2f78)

Kindly assign this issue to me.
@varun-singhh @SourabhKanade

**Comment by Titiksha2012** [comment]
Kindly assign this issue to me.
@varun-singhh @SourabhKanade

**Comment by kaustubhai** [comment]
This is according to our design guidelines. Dont need this to change yet.
