### ISSUE TITLE
Alignment of Newsletter Input box and Subscribe button is not good  [GsSOC'23]

### ISSUE THREAD

**Issue by Monilprajapati** [Deveimer/vovoca-frontend#123]
## Issue Description

There's an issue with the alignment of input text field and the Submit button in the Newsletter section (Footer). I'll solve that issue by making some simple changes into Footer CSS.

## Expected Behavior

After applying this changes in the footer section, the input text and the submit button will become more user friendly.

## Current Behavior

Currently the alignment of input text field and the submit button is not looking good because of the bad alignment of submit button.

## Possible Solution (optional)

1. I'll Change some CSS Positioning Properties.
2. I'll also make some changes into padding of the button.

## Before : 
![image](https://github.com/Deveimer/vovoca-frontend/assets/99136041/55528d05-33d8-4da0-96d1-b9dff80db684)

## After :
![image](https://github.com/Deveimer/vovoca-frontend/assets/99136041/292d1f8d-1b09-44ff-9f39-e0af92a1bc31)

**Comment by kaustubhai** [comment]
On which page and what screen size are you seeing this?

**Comment by Monilprajapati** [comment]
> On which page and what screen size are you seeing this?

On all the pages it seems the same.
It's on full screen (1490 x 705). I can make it responsive.

**Comment by varun-singhh** [comment]
@Monilprajapati assigned

**Comment by Monilprajapati** [comment]
Hey @varun-singhh Is this Repo still active? So i can resolve this Issue and raise the PR.
