### ISSUE TITLE
Add workflow to close issue >30 days

### ISSUE THREAD

**Issue by Abhinavcode13** [Deveimer/vovoca-frontend#131]
## Issue Description

It is basically going to close the old issue which are not relevant and not worked on automatically once it reaches 30 days.

## Steps to Reproduce (if applicable)

GitHub Actions to create a workflow that runs on a schedule (e.g., every day) and checks the creation or last update timestamp of the issues. If the issue exceeds the 30-day threshold, the workflow can call the GitHub API to close the issue.

**Comment by Abhinavcode13** [comment]
@varun-singhh please assign me this issue under gssoc
thanks buddy

**Comment by kaustubhai** [comment]
Not required. Thanks
