### ISSUE TITLE
CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by parthpathakpp1** [Deveimer/vovoca-frontend#132]
## Issue Description
There is no CODE OF CONDUCT in the repo . 

## Expected Behavior

There should be a CODE OF CONDUCT . Which will give guidelines to the contributors . 

## Current Behavior

There is no CODE OF CONDUCT currently . 

## Possible Solution (optional)

I will make a CODE_OF_CONDUCT.md for the contributors . 

## Additional Context (optional)

[Add any other relevant information here, such as screenshots, related issues, or notes.]

**Comment by kaustubhai** [comment]
Not required. Thanks
