### ISSUE TITLE
Want to give animation effect on homa page image

### ISSUE THREAD

**Issue by HimanshuNarware** [Deveimer/vovoca-frontend#133]
## Issue Description
The home page image of the boy is missing an animation effect.

## Steps to Reproduce (if applicable)

1. [add animation effect on the image]
2. [ also give hover effect to the image]

## Expected Behavior
 I want to give an animation effect to the image and the hover effect  on the image, In an animation effect the image is moving in Y-direction also when someone hovers over the image it responds according to the cursor

## Current Behavior
No animation effect
No hover effect

## Possible Solution (optional)
Added animation and hover effect
## Additional Context (optional)
##Screenshot
![168](https://github.com/Deveimer/vovoca-frontend/assets/83147410/e6691401-96e7-4210-876e-803e25c5b749)

**Comment by kaustubhai** [comment]
Not required. Thanks
