### ISSUE TITLE
"Login" Button Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [Deveimer/vovoca-frontend#18]
The design of the "Login" button is nice but the underline effect is not looking good and somehow making the user think of purpose of this effect. By removing or modifying its design, the button will look even better.

I want to work on this improvement as a part of GSSOC-23.

**Comment by varun-singhh** [comment]
Can you be more specific and please tell what you are trying to say

**Comment by iamRabia-N** [comment]
Hi @varun-singhh
The border effect of "Login" button looks like an underline.
Check the difference in current and expected updated design.

**Current Design**
![vovoca ss (2)](https://github.com/Deveimer/vovoca-frontend/assets/115794049/1cd5db3e-40fd-416d-9e99-34abc5d3a1ba)

**Updated Design**
![vovoca ss (1)](https://github.com/Deveimer/vovoca-frontend/assets/115794049/0f719c4f-5ab4-4384-9140-f01d53bee4c2)

**Comment by varun-singhh** [comment]
@iamRabia-N 
Okay, Can you tell me in which browser is it happening, because for me it's working perfectly fine in safari, chrome and firefox

**Comment by iamRabia-N** [comment]
Chrome

**Comment by varun-singhh** [comment]
yes I can see but after logging in. So yes you can take up the issue. Assigning u.
