### ISSUE TITLE
Homepage Text Alignment

### ISSUE THREAD

**Issue by iamRabia-N** [Deveimer/vovoca-frontend#19]
The homepage is looking nice but it can be improved by making some alignment adjustments in the homepage text. Through proper alignment and other changes on the text, I can make homepage look even better.

I want to work on this improvement as a part of GSSOC-23.

**Comment by kaustubhai** [comment]
Any references on figma/dribbble/behance you would follow for this design enhancement? 

**PRO-TIP:** If its a small change, you can tweak alignments on browser and share screenshot for us to decide either we want it or not

**Comment by iamRabia-N** [comment]
Hi @kaustubhai 
Check out screenshots and share your review.
I haven't work on the button. But the button (in updated design) needs to be moved little bit on upward direction.


### Current Design
![vovoca ss (1)](https://github.com/Deveimer/vovoca-frontend/assets/115794049/c9b0f9b7-7293-4272-952d-5e46b4ed9460)

### Updated Design
![vovoca ss (2)](https://github.com/Deveimer/vovoca-frontend/assets/115794049/415fe0d5-a5da-4ba1-a46e-467cd9e1af04)

**Comment by kaustubhai** [comment]
This varies from screen to screen. On my big screen it is looking fine as your desired output. Hence, closing this issue
