### ISSUE TITLE
[Feature] Footer Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [Deveimer/vovoca-frontend#2]
This site should I have a Footer section .

**Why Footer Section should be there ? -:**

1 .Navigation and Site Map: The footer provides easy navigation and a site map, helping users find information quickly.

2. Contact Information: Display important contact details like phone numbers, email addresses, and social media links.

3. Additional Links and Resources: Showcase related links, partners, and important pages that don't fit in the main navigation.

4. Copyright and Legal Information: Include copyright notices, disclaimers, and terms of service to protect intellectual property and ensure compliance.

**Requirements - :**
1.Your Social media links .

I will make a good Footer section for your website .

**Comment by parthpathakpp1** [comment]
Assign me this issue under GSSOC'23.

**Comment by varun-singhh** [comment]
assigned @parthpathakpp1 

Make sure on creating PR branch name should be of specific format, 
`VOVOCA-issueNumber`

e.g for this issue number is 2 so
`VOVOCA-2`

**Comment by parthpathakpp1** [comment]
> assigned @parthpathakpp1
> 
> Make sure on creating PR branch name should be of specific format, `VOVOCA-issueNumber`
> 
> e.g for this issue number is 2 so `VOVOCA-2`

OK
