### ISSUE TITLE
Issue: Scroll back to top button problem

### ISSUE THREAD

**Issue by DivyanshiNarang** [Deveimer/vovoca-frontend#25]
Scroll back to the top button getting hidden behind Trending and Contacts sections.

## Expected Behavior
It should be visible throughout the page for the user to get back to the top at any point.

https://github.com/Deveimer/vovoca-frontend/assets/74779601/c752fa90-3215-43f6-8bb0-9aed9ce6917c

*Please assign this to me under GSSoC'23* @varun-singhh

**Comment by varun-singhh** [comment]
Good found, Assigned you can work on it 

Make sure to follow contributing guidelines and PR guidelines

**Comment by varun-singhh** [comment]
Assigning Due Date as 31st May. Also Change the status to `in progress` once you start working

**Comment by parthpathakpp1** [comment]
@DivyanshiNarang I need some help . Can you share your Discord id please .

**Comment by DivyanshiNarang** [comment]
> @DivyanshiNarang I need some help . Can you share your Discord id please .

divya#0934

**Comment by parthpathakpp1** [comment]
> divya#0934

check dm.

**Comment by DivyanshiNarang** [comment]
Hello @varun-singhh, Please tell me how to change the status to 'in progress'.

**Comment by varun-singhh** [comment]
> Hello @varun-singhh, Please tell me how to change the status to 'in progress'.

in the right section you can see Assignee's Labels, and projects.

Under projects you can click the down arrow button to see status, project type and due date

**Comment by varun-singhh** [comment]
Merged
