### ISSUE TITLE
Enhancement: Add hovering effect on the heading.

### ISSUE THREAD

**Issue by DivyanshiNarang** [Deveimer/vovoca-frontend#26]
Adding a hovering effect on the heading "Welcome to Vovoca" or to "Royalty Free Music".

<img width="372" alt="image" src="https://github.com/Deveimer/vovoca-frontend/assets/74779601/8cbcd2e9-20db-4e44-916a-970a646cc719">

<img width="477" alt="Screenshot 2023-05-26 175139" src="https://github.com/Deveimer/vovoca-frontend/assets/74779601/7c64604d-1b17-4196-ad99-66a01aef1360">

**Sample:**

https://github.com/Deveimer/vovoca-frontend/assets/74779601/31ca4b2a-4921-4922-bd99-b106873df1a1

         

Please suggest, if any other.

"*Please assign this issue to me under GSSoC'23*"

**Comment by varun-singhh** [comment]
no a requirement, closing the issue
