### ISSUE TITLE
Hovering on Button.

### ISSUE THREAD

**Issue by parthpathakpp1** [Deveimer/vovoca-frontend#3]
Color of Buttons should be different while hovering . 
**I think this color will look good on buttons while hovering .**
![vovoca](https://github.com/Deveimer/vovoca-frontend/assets/85991449/8d038f1f-0155-468b-8eec-7387d23d1a65)

**Comment by parthpathakpp1** [comment]
Assign me this issue under GSSOC'23.

**Comment by varun-singhh** [comment]
sorry but this is the UI which we are going to follow, can't assign this
