### ISSUE TITLE
[Improvement] Fix Copyright year to be dynamic in Contacts card [GSSoC'23]

### ISSUE THREAD

**Issue by vishnu9865** [Deveimer/vovoca-frontend#32]
## Issue Description
The copyright year is hardcoded

## Expected Behavior
The Year should dynamically update to the current year in the contacts section.

## Current Behavior
The copyright section still has the year 2021 in it.

![image](https://github.com/Deveimer/vovoca-frontend/assets/91585213/f6947751-42fb-4376-ae1a-a2b83cf60c12)

**Comment by vishnu9865** [comment]
@varun-singhh Sir,
I would like to work on this issue. So please assign me this under GSSoC'23.
Thanks in advance.
Regards,
Jeyavishnu @vishnu9865

**Comment by varun-singhh** [comment]
okay you can work on it. assigned

**Comment by vishnu9865** [comment]
@varun-singhh Thank you for assigning me.
😊👍
