### ISSUE TITLE
Adding hover and shadow effects to testimonial cards

### ISSUE THREAD

**Issue by mukul314** [Deveimer/vovoca-frontend#33]
Currently when we hover over the cards in the testimonial sections, nothing happens. We can a nice scaling effect which will make the cards grow on hovering, and along with that some shadow effects can also be added.

This will make the website more eye catchy.
@varun-singhh , I'd like to work on this if you approve!!

**Comment by varun-singhh** [comment]
not a requirement now. closing the issue
