### ISSUE TITLE
Refactor: generate link components using map method

### ISSUE THREAD

**Issue by kailashchoudhary11** [Deveimer/vovoca-frontend#35]
The same code is copy pasted for all the link components in index.js file.
We can store size and href of link in array of objects and map through it to generate link elements dynamically.

**Comment by varun-singhh** [comment]
can you be more specific and attach the screenshot for the reference.

**Comment by kailashchoudhary11** [comment]
@varun-singhh I mean all these components have the same format and code just the `href` and `size` are changing.
We can create array of objects where each object will have `href` and `size` keys. We can map over this array to create all of the link elements.
![image](https://github.com/Deveimer/vovoca-frontend/assets/75559082/3d15361b-29ae-4116-83c1-6c34e83e551c)

**Comment by varun-singhh** [comment]
yes we can do that, okay you can take it. assigned @kailashchoudhary11
