### ISSUE TITLE
Get In Touch Section is not Centered [GSSoC'23]

### ISSUE THREAD

**Issue by ritik48** [Deveimer/vovoca-frontend#36]
## Issue Description

Get In Touch section is not centered.

## Current Behavior

![vovoca get in touch centring issue](https://github.com/Deveimer/vovoca-frontend/assets/84488726/0f2bbc9f-394e-490f-8805-31ed8434e535)

Please assign this issue to me under GSSoC'23.

**Comment by varun-singhh** [comment]
sorry but now it is not meant to be centered. It is as per designs only. It you can suggest some specif way to align then it would be helpful.

**Comment by ritik48** [comment]
@varun-singhh actually I raised this issue because it's not aligning with the above sections

**Comment by varun-singhh** [comment]
that is already as per design, you can work on other issues. Will discuss if there is any such requirement will re-open the issue, closing this for now.
