### ISSUE TITLE
Adding sign up functionality with google, facebook etc

### ISSUE THREAD

**Issue by mukul314** [Deveimer/vovoca-frontend#39]
Currently, there is no option for signing up through google, facebook or github. By adding this it will be easier for users when signing up or logging in.

Something like this maybe?
<img width="459" alt="2023-05-27 21_38_42-Holiday Homes   Apartment Rentals - Airbnb - Airbnb - Brave" src="https://github.com/Deveimer/vovoca-frontend/assets/76463001/3c113962-71ec-419c-8339-c4acc9fe3dc9">

@varun-singhh , I'd like to work on this if you think the issue is relevant.

**Comment by varun-singhh** [comment]
not a requirement.
