### ISSUE TITLE
Hovering Effect

### ISSUE THREAD

**Issue by parthpathakpp1** [Deveimer/vovoca-frontend#4]
We can add a hovering effect on contributors section . Currently it looks very static and does not do any action while hovering . 
![vovacadfd](https://github.com/Deveimer/vovoca-frontend/assets/85991449/7124a0df-026c-4510-b4bb-8a60d8ab224d)

**Comment by parthpathakpp1** [comment]
Assign me this under GSSOC'23.

**Comment by varun-singhh** [comment]
already assigned you one issue, and someone already working on the same. Closing the issue
