### ISSUE TITLE
[ENHANCEMENT] Selecting Categories doesn't not show expected behavior 

### ISSUE THREAD

**Issue by varun-singhh** [Deveimer/vovoca-frontend#40]
## Selecting Categories doesn't not show expected behavior

On selecting categories the color of categories should change and the category should scale down. but it is not working

## Steps to Reproduce (if applicable)

1. Login and visit you dashboard to see categories

## Expected Behavior

One can see the behavior of clicking on categories
https://user-images.githubusercontent.com/47475007/114043261-c230c780-98a3-11eb-8526-7a39f52f5b72.gif

## Current Behavior (SS)
<img width="228" height="456" alt="Screenshot 2023-05-27 at 9 29 02 PM" src="https://github.com/Deveimer/vovoca-frontend/assets/47475007/9389c49e-1cc4-42a8-b7bf-3ee675aec86f">

**Comment by vishnu9865** [comment]
@varun-singhh  Sir,
I would like to work on this issue.
I have implemented it in a project before.
Could you kindly assign it to me under GSSoC'23

**Comment by varun-singhh** [comment]
@vishnu9865 assigned
