### ISSUE TITLE
Web Service not available in tablet mode

### ISSUE THREAD

**Issue by itshypon** [Deveimer/vovoca-frontend#41]
## Issue Description
When we change the width and height of page for tablet view, it shows that web service is not available for tablet view.

## Steps to Reproduce (if applicable)

1. Inspect Element of website
2. Change height and width or responsiveness to tablet

## Expected Behavior

Website should load for tablet devices also.

## Current Behavior
![image](https://github.com/Deveimer/vovoca-frontend/assets/30335924/7e5ada2d-2e3a-48dd-a8ab-04b28d716c92)

**Comment by varun-singhh** [comment]
@itshypon assigned

**Comment by itshypon** [comment]
Hey @varun-singhh, this task is already divided into subtasks in recent issues so I will un-assign it and work on other issues for now.
