### ISSUE TITLE
Redundant 'onClick' handling

### ISSUE THREAD

**Issue by itshypon** [Deveimer/vovoca-frontend#42]
## Issue Description
'onClick' handler is used two times for one element inside Navbar (Navbar.jsx) when logging out. It may lead to conflicts in future.

## Steps to Reproduce (if applicable)

1. Clone the repo and check Navbar.jsx

## Current Behavior
![image](https://github.com/Deveimer/vovoca-frontend/assets/30335924/b612fe10-1c5b-4f0a-b551-0c099aca9129)
![image](https://github.com/Deveimer/vovoca-frontend/assets/30335924/b9eb5825-cafa-4e2f-ae1a-8dab52749e14)

**Comment by varun-singhh** [comment]
assigned @itshypon
