### ISSUE TITLE
Header element's alignment is incorrect

### ISSUE THREAD

**Issue by SoumyadeepOSD** [Deveimer/vovoca-frontend#48]
## Issue Description

During responsive check I tested it for "iphone XE" and it shown the tab element incorrect alignment error

## Steps to Reproduce (if applicable)

1. Open the link `https://vovoca-frontend-deploy.vercel.app/`
2. Right-click + inspect and check for `iphone XE`
3. You will find the error

## Expected Behavior

Header elements should be aligned properly in linear manner

## Current Behavior

Header elements are not aligned properly

## Possible Solution (optional)

Header elements should be placed in such a way, whenever the screen will be in mobile version, a 3 dot menu icon will appear to show the elements in dropdown format

## Additional Context (optional)

![image](https://github.com/Deveimer/vovoca-frontend/assets/115442240/48b05df7-5644-484f-b06f-6c911c5778fe)

**Comment by varun-singhh** [comment]
already issue is opened check #38 . Closing this you can comment on that issue if you want it to be assigned.
