### ISSUE TITLE
Grammatical errors in some areas of the site

### ISSUE THREAD

**Issue by mukul314** [Deveimer/vovoca-frontend#51]
There are some grammatical mistakes that I want to highlight, for example, look at the below image:

<img width="250" alt="2023-05-28 07_31_13-VOVOCA _ Home - Brave" src="https://github.com/Deveimer/vovoca-frontend/assets/76463001/81a1efd9-df5e-481c-832a-3f59a705c289">

Here, vidoes should be videos .

Another place where there is an error is :

<img width="231" alt="2023-05-28 07_32_36-VOVOCA _ Team - Brave" src="https://github.com/Deveimer/vovoca-frontend/assets/76463001/a629b849-d86d-4525-bb9c-952c6bb7b35b">

Here decidation should be dedication.

Another place is this :

<img width="277" alt="2023-05-28 08_17_37-VOVOCA _ Home - Brave" src="https://github.com/Deveimer/vovoca-frontend/assets/76463001/c2e5594d-bce4-4d92-985f-f9463da51459">

feilds should be fields

@varun-singhh , I'd like to work on this issue and correct the errors.

**Comment by varun-singhh** [comment]
assigned
