### ISSUE TITLE
Bug: Contributors fetched incorrectly

### ISSUE THREAD

**Issue by kailashchoudhary11** [Deveimer/vovoca-frontend#52]
The contributors' section on the `developers` page does not contain all the contributors. Cause we are not fetching the contributors of the current repo instead we're fetching contributors of `https://github.com/varun-singhh/vovoca`. So this has to be refactored and we'll have to fetch the contributors from the backend repo as well. After that take the unique contributors from both the repos cause the same contributor might have contributed to both the repos.  We can then show all the contributors.

**Comment by varun-singhh** [comment]
assigned
