### ISSUE TITLE
Bug: id attribute used twice on an element.

### ISSUE THREAD

**Issue by kailashchoudhary11** [Deveimer/vovoca-frontend#57]
The id attribute is used twice over here. It should be used only once
![image](https://github.com/Deveimer/vovoca-frontend/assets/75559082/cd6669d0-9477-4081-b9b9-d57eafa53ce6)

**Comment by Vidit-Jain2206** [comment]
can you assign me this issue.

**Comment by varun-singhh** [comment]
@kailashchoudhary11 assigned.
