### ISSUE TITLE
Add animation and hover effect on cards

### ISSUE THREAD

**Issue by sumitkr2000** [Deveimer/vovoca-frontend#58]
## Issue Description

Hey @SourabhKanade I want to add hover effect on cards and add animation to the website. Please assign me this issue. Thank you!

## Steps to Reproduce (if applicable)

1. Add box shadow to cards
2. animation to divs
3. Proper footer

## Expected Behavior

[Describe what you expected to happen.]

## Current Behavior

[Describe what actually happened.]

## Possible Solution (optional)

[Provide suggestions or ideas for how to address this issue.]

## Additional Context (optional)

[Add any other relevant information here, such as screenshots, related issues, or notes.]

**Comment by varun-singhh** [comment]
Could you please demo the animation which you are willing to add.

**Comment by sumitkr2000** [comment]
@varun-singhh Yeah please give me some time.

**Comment by sumitkr2000** [comment]
@varun-singhh I want to add aos.

**Comment by sumitkr2000** [comment]
Can you assign me this issue?

**Comment by SurbhiMotwani23** [comment]
kindly assign me this issue
