### ISSUE TITLE
Add Depandabot to project

### ISSUE THREAD

**Issue by k-deepak04** [Deveimer/vovoca-frontend#7]
Integrating Dependabot into our project will automate dependency management, ensuring our dependencies are regularly updated to their latest versions. This will enhance security, stability, and maintainability by addressing vulnerabilities and taking advantage of new features and bug fixes.
Please assign this to me

**Comment by varun-singhh** [comment]
this we had in mind we will be adding it but in phase 2. Not closing this issue will assign it later

**Comment by k-deepak04** [comment]
okay :)

**Comment by k-deepak04** [comment]
@varun-singhh shall we proceed with this?

**Comment by k-deepak04** [comment]
i have 2 more automation bots that can really help in maintain this repo
close old issues bot and greeting bot
