### ISSUE TITLE
[ENHANCEMENT] FIx linting errors in dev

### ISSUE THREAD

**Issue by kailashchoudhary11** [Deveimer/vovoca-frontend#72]
We can add EsLint and Husky to perform pre-commit checks and verify that the quality of the code is maintained. 
If the quality of the code is not as per the rules defined in the EsLint config file, the commit will be rejected.
This will help us in maintaining the quality of code throughout the code base. We can configure EsLint as per the prettier config.

**Comment by varun-singhh** [comment]
@kailashchoudhary11 if there are other issues assigned to you fix those raise the PR then only I can assign you new one. Btw this is required you can work on it.

**Comment by kailashchoudhary11** [comment]
I've already made PRs for the assigned issues. @varun-singhh Kindly review them.

**Comment by varun-singhh** [comment]
can you ping your PR link here

**Comment by kailashchoudhary11** [comment]
@varun-singhh this should be `level3`

**Comment by varun-singhh** [comment]
@kailashchoudhary11 we had some specifications in linters so I already added that, so I am changing this issue name to Fix linters. there are linting issues in dev please fix those.
