### ISSUE TITLE
[DOCS] Add Contributors Graph

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [Deveimer/vovoca-frontend#77]
* I would like to incorporate a contributor graph in the README.md file as a means of acknowledging and appreciating the work of contributors. I kindly request to be assigned this particular issue.
* Here is an example of the work I aspire to undertake within this project.

![Screenshot (80)](https://github.com/Deveimer/vovoca-frontend/assets/112751524/7a026b43-ff91-4bcf-998e-48628117c6c7)

**Comment by varun-singhh** [comment]
okay @Shiva-Sai-ssb assigned
