### ISSUE TITLE
add Code of conduct 

### ISSUE THREAD

**Issue by S-ishita** [Deveimer/vovoca-frontend#78]
## Issue Description

Hi there!
I recommend adding a CODE_OF_CONDUCT.md file to your repository. 

## Expected Behavior

This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

## Possible Solution (optional)

Adding a code of conduct file would be a possible solution

## Additional Context (optional)

I would like to work on this issue. Please assign it to me under GSSoC'23.

Thank you!

**Comment by varun-singhh** [comment]
already there. Closing the issue
