### ISSUE TITLE
EFFECTS ON ALL CARDS

### ISSUE THREAD

**Issue by ashutoshgithubs** [Deveimer/vovoca-frontend#8]
I observed that there are no special effects like scaling while hovering over cards are there.
I have worked on a website where I developed a feature like when you hover over a card it will scale up with smooth transition and there will appear a wavy icon. You can see this on my website https://razorpayclonebyashu.netlify.app/
So please assign me this task under GSSOC'23 Label. I will develop it to a next level
Thank you

**Comment by varun-singhh** [comment]
not required rn, closing the issue
