### ISSUE TITLE
Providing a "NO" option while logging out

### ISSUE THREAD

**Issue by mukul314** [Deveimer/vovoca-frontend#81]
Currently when the user tries to logout then he is asked if he is sure, but there is no other option like "NO". I guess there should be an another option like "NO, KEEP ME LOGGED IN" or something like that so that the user can go back if he does not wants to log out.

See the below image for more context :

<img width="344" alt="2023-05-29 21_35_31-VOVOCA _ Welcome to Dashboard - Brave" src="https://github.com/Deveimer/vovoca-frontend/assets/76463001/8b519243-8a24-4a4a-904a-f54d1324f40b">

Note that the above image is only for representation purposes, the original button will be according to the website's theme.

@varun-singhh , I'd like to work on this issue if you approve.

**Comment by varun-singhh** [comment]
not a requirement because we have already an option to go back. This could have been possible in a popup. so closing issue now
