### ISSUE TITLE
Light mode - Dark mode feature

### ISSUE THREAD

**Issue by ashutoshgithubs** [Deveimer/vovoca-frontend#9]
Hello Project Admin, If we integrate light mode - dark mode switch feature then it will enhance UI to a next level.
I have worked on this feature before and my work is here :https://ashutecher.co/ You can review my work.
So, please assign me this task under GSSOC'23 label.

**Comment by kaustubhai** [comment]
@ashutoshgithubs dont think we want it. UI is designed for dark mode, not sure how it will look like in light. Any references you will follow on figma/behance/dribbble, etc?
